[tool.poetry]
name = "Rangekeeper"
version = "0.6.3-alpha"
description = "A Python library assisting financial modelling in scenario planning, decision-making, cashflow forecasting, and the like"
authors = ["Daniel Fink <danfink@mit.edu>"]
license = "MPL-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
matplotlib = "^3.9.0"
pandas = "^2.2.2"
pint = "^0.23"
pyxirr = "^0.10.3"
scipy = "^1.13.1"
networkx = "^3.3"
py-moneyed = "^3.0"
tabulate = "^0.9.0"
pyyaml = "^6.0.1"
specklepy = "^2.19.0"
numba = "^0.59.1"
multiprocess = "^0.70.16"
seaborn = "^0.13.2"
pyvis = "^0.3.2"
plotly = "^5.22.0"
mpld3 = "^0.5.10"
pyarrow = "^16.1.0"

[tool.poetry.dev-dependencies]
pytest = "^8.2.1"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
